---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install a package from the free repository
      ansible.builtin.package:
        name: rpmfusion-free-release-tainted
        state: present

    - name: Install a package from the nonfree repository
      ansible.builtin.package:
        name: rpmfusion-nonfree-release-tainted
        state: present
